const { contextBridge, ipcRenderer } = require('electron');

contextBridge.exposeInMainWorld('electronAPI', {
    openExternal: (url) => ipcRenderer.invoke('open-external', url),
    onWindowFocused: (callback) => ipcRenderer.on('window-focused', callback),
    closeWindow: () => ipcRenderer.invoke('close-window'),
    minimizeWindow: () => ipcRenderer.invoke('minimize-window'),
    maximizeWindow: () => ipcRenderer.invoke('maximize-window'),
    openModsFolder: () => ipcRenderer.invoke('open-mods-folder'),
    launchSpore: () => ipcRenderer.invoke('launch-spore'),
    openDiscord: () => ipcRenderer.invoke('open-discord'),
    openKofi: () => ipcRenderer.invoke('open-kofi'),
    updateLauncher: () => ipcRenderer.send('quit-and-install'),
    onUpdateAvailable: (callback) => ipcRenderer.on('update-available', callback),
    downloadUpdate: () => ipcRenderer.invoke('download-update'),
    onUpdateDownloaded: (callback) => ipcRenderer.on('update-downloaded', callback),
    getAppVersion: () => ipcRenderer.invoke('get-app-version'),
    setInstalling: (installing) => ipcRenderer.invoke('set-installing', installing),
    setLanguage: (lang) => ipcRenderer.invoke('set-language', lang),
    showConfirm: (options) => ipcRenderer.invoke('show-confirm', options),
    isUnlock60fpsInstalled: () => ipcRenderer.invoke('is-unlock60fps-installed'),
    uninstallUnlock60fps: () => ipcRenderer.invoke('uninstall-unlock60fps'),
    installSporemod: (modDir, zipPath) => ipcRenderer.invoke('install-sporemod', modDir, zipPath),
    downloadModWithProgress: (url) => ipcRenderer.invoke('download-mod-with-progress', url),
    onModDownloadProgress: (callback) => ipcRenderer.on('mod-download-progress', (_e, progress) => callback(progress)),
    onModInstallProgress: (callback) => ipcRenderer.on('mod-install-progress', (_e, progress) => callback(progress)),
    unzipMod: (zipPath) => ipcRenderer.invoke('unzip-mod', zipPath),
    onWindowMaximizeChanged: (callback) => ipcRenderer.on('window-maximize-changed', callback),
    isHDTexturesInstalled: () => ipcRenderer.invoke('is-hdtextures-installed'),
    installHDTextures: (extractedPath, zipPath) => ipcRenderer.invoke('install-hdtextures', extractedPath, zipPath),
    uninstallHDTextures: () => ipcRenderer.invoke('uninstall-hdtextures'),
    is4gbPatchInstalled: () => ipcRenderer.invoke('is-4gbpatch-installed'),
    install4gbPatch: (extractedPath, zipPath) => ipcRenderer.invoke('install-4gbpatch', extractedPath, zipPath),
    uninstall4gbPatch: () => ipcRenderer.invoke('uninstall-4gbpatch'),
    uninstallAllMods: () => ipcRenderer.invoke('uninstall-all-mods'),
});