const { contextBridge, ipcRenderer } = require('electron');

contextBridge.exposeInMainWorld('electronAPI', {
    openExternal: (url) => ipcRenderer.invoke('open-external', url),
    onWindowFocused: (callback) => ipcRenderer.on('window-focused', callback),
    closeWindow: () => ipcRenderer.invoke('close-window'),
    minimizeWindow: () => ipcRenderer.invoke('minimize-window'),
    maximizeWindow: () => ipcRenderer.invoke('maximize-window'),
    openModsFolder: () => ipcRenderer.invoke('open-mods-folder'),
    launchSpore: () => ipcRenderer.invoke('launch-spore'),
    launchSporeBase: () => ipcRenderer.invoke('launch-spore-base'),
    openDiscord: () => ipcRenderer.invoke('open-discord'),
    openKofi: () => ipcRenderer.invoke('open-kofi'),
    updateLauncher: () => ipcRenderer.send('quit-and-install'),
    onUpdateAvailable: (callback) => ipcRenderer.on('update-available', callback),
    downloadUpdate: () => ipcRenderer.invoke('download-update'),
    onUpdateDownloaded: (callback) => ipcRenderer.on('update-downloaded', callback),
    getAppVersion: () => ipcRenderer.invoke('get-app-version'),
    setInstalling: (installing) => ipcRenderer.invoke('set-installing', installing),
    setLanguage: (lang) => ipcRenderer.invoke('set-language', lang),
    showConfirm: (options) => ipcRenderer.invoke('show-confirm', options),
    getSporeInstallations: () => ipcRenderer.invoke('get-spore-installations'),
    hasSporeBase: () => ipcRenderer.invoke('has-spore-base'),
    hasSporeGA: () => ipcRenderer.invoke('has-spore-ga'),
    isUnlock60fpsInstalled: (gameType) => ipcRenderer.invoke('is-unlock60fps-installed', gameType),
    uninstallUnlock60fps: (gameType) => ipcRenderer.invoke('uninstall-unlock60fps', gameType),
    installSporemod: (modDir, zipPath, gameType) => ipcRenderer.invoke('install-sporemod', modDir, zipPath, gameType),
    downloadModWithProgress: (url, gameType, installId) => ipcRenderer.invoke('download-mod-with-progress', url, gameType, installId),
    onModDownloadProgress: (callback) => ipcRenderer.on('mod-download-progress', (_e, progress) => callback(progress)),
    removeModDownloadProgress: (callback) => ipcRenderer.removeListener('mod-download-progress', callback),
    onModInstallProgress: (callback) => ipcRenderer.on('mod-install-progress', (_e, progress) => {
        callback(progress);
    }),
    removeModInstallProgress: (callback) => ipcRenderer.removeListener('mod-install-progress', callback),
    unzipMod: (zipPath) => ipcRenderer.invoke('unzip-mod', zipPath),
    unzipModTo: (zipPath, extractPath) => ipcRenderer.invoke('unzip-mod-to', zipPath, extractPath),
    onWindowMaximizeChanged: (callback) => ipcRenderer.on('window-maximize-changed', callback),
    isHDTexturesInstalled: (gameType) => ipcRenderer.invoke('is-hdtextures-installed', gameType),
    installHDTextures: (extractedPath, zipPath, gameType, installId) =>
        ipcRenderer.invoke('install-hdtextures', extractedPath, zipPath, gameType, installId),
    uninstallHDTextures: (gameType) => ipcRenderer.invoke('uninstall-hdtextures', gameType),
    is4gbPatchInstalled: (gameType) => ipcRenderer.invoke('is-4gbpatch-installed', gameType),
    install4gbPatch: (extractedPath, zipPath, gameType) => ipcRenderer.invoke('install-4gbpatch', extractedPath, zipPath, gameType),
    uninstall4gbPatch: (gameType) => ipcRenderer.invoke('uninstall-4gbpatch', gameType),
    uninstallAllMods: () => ipcRenderer.invoke('uninstall-all-mods'),
    onModUnzipProgress: (callback) => ipcRenderer.on('mod-unzip-progress', (_e, progress) => callback(progress)),
    removeModUnzipProgress: (callback) => ipcRenderer.removeListener('mod-unzip-progress', callback),
});